#config_version=5
mode:
  start_events: boss1_start, ball_save_intro_disabled
  stop_events: timer_boss1_timeout_timer_complete, boss1_success
  priority: 200

widgets:
      bossfight:
        - type: text
          text: BossHits (boss1hits)
          number_grouping: true
          min_digits: 2
          font_size: 16
          x: middle
          y: top-30
          anchor_x: left
          anchor_y: top
        - type: text
          text: BOSSBATTLE
          x: middle
          y: top
          font_size: 18
          anchor_x: middle
          anchor_y: top
  
widget_player:
    mode_boss1_started:
      bossfight:
        slide: main_scoring_slide  

timers:
    boss1_timeout_timer:
        start_value: 60
        end_value: 0
        direction: down
        tick_interval: 1s
        start_running: true  
  
variable_player:
    shot_ring_hit:
        score: 5000
        boss1hits: 1
        
        
event_player:
   shot_ring_hit{current_player.boss1hits >= 10}: boss1_success
