#config_version=5
mode:
  start_events: supersling_start
  stop_events: timer_super_sling_timer_complete
  priority: 200

  

timers:
    super_sling_timer:
        start_value: 30
        end_value: 0
        direction: down
        tick_interval: 1s
        start_running: true  
  
variable_player:
    shot_l_sling_hit:
        score: 300
        slings: 1
    shot_r_sling_hit:
        score: 400
        slings: 1