#config_version=5
mode:
  start_events: supersling_start
  stop_events: timer_super_sling_timer_complete
  priority: 200

widgets:
      superslingslide:
        - type: text
          font_name: hachicro
          text: Slings (slings)
          number_grouping: true
          min_digits: 2
          font_size: 16
          x: left
          y: top-30
          anchor_x: left
          anchor_y: top
        - type: text
          text: SUPERSLINGS
          x: left
          y: top
          font_size: 18
          anchor_x: left
          anchor_y: top
  
widget_player:
    mode_supersling_started:
      superslingslide:
        slide: main_scoring_slide

  

timers:
    super_sling_timer:
        start_value: 30
        end_value: 0
        direction: down
        tick_interval: 1s
        start_running: true  
  
variable_player:
    shot_l_sling_hit:
        score: 300
        slings: 2
    shot_r_sling_hit:
        score: 400
        slings: 2