#config_version=5
mode:
  start_events: supersling_start
  stop_events: timer_super_sling_timer_complete
  priority: 200

slide_player:
    mode_supersling_started:
      superslingslide:
        - type: text
          font_name: hachicro
          text: Slings (slings)
          number_grouping: true
          min_digits: 2
          font_size: 10
        - type: text
          text: SUPERSLINGS
          font_size: 25
          anchor_x: left
          anchor_y: bottom
  

timers:
    super_sling_timer:
        start_value: 30
        end_value: 0
        direction: down
        tick_interval: 1s
        start_running: true  
  
variable_player:
    shot_l_sling_hit:
        score: 300
        slings: 1
    shot_r_sling_hit:
        score: 400
        slings: 1