#config_version=5
mode:
  start_events: superspinner_start
  stop_events: timer_super_spinner_timer_complete
  priority: 200

widgets:
      superspinnerslide:
        - type: text
          font_name: hachicro
          text: Spins (spinners)
          number_grouping: true
          min_digits: 2
          font_size: 16
          x: left
          y: top-60
          anchor_x: left
          anchor_y: top
        - type: text
          text: SUPERSPINNERS
          x: left
          y: top-40
          font_size: 18
          anchor_x: left
          anchor_y: top
  
widget_player:
    mode_superspinner_started:
      superspinnerslide:
        slide: main_scoring_slide  

timers:
    super_spinner_timer:
        start_value: 30
        end_value: 0
        direction: down
        tick_interval: 1s
        start_running: true  
  
variable_player:
    shot_l_spinner_profile_spinner_hit:
        score: 5000
        spinners: 2
    shot_r_spinner_profile_spinner_hit:
        score: 5000
        spinners: 2