#config_version=5
mode:
  start_events: mode_spinner_type_start
  stop_events: spinner_type_heart_selected, spinner_type_power_selected, spinner_type_multiply_selected
  code: mpf.modes.carousel.code.carousel.Carousel
  priority: 200

mode_settings:
  selectable_items: heart, power, multiply
#  select_item_events: s_launch_active
  next_item_events: s_flipper_right_b_active
  previous_item_events: s_flipper_left_b_active

slide_player:
  spinner_type_heart_highlighted: select_heart
  spinner_type_power_highlighted: select_power
  spinner_type_multiply_highlighted: select_multiply

show_player:
  spinner_type_heart_highlighted: select_heart
  spinner_type_power_highlighted: select_power
  spinner_type_multiply_highlighted: select_multiply
  
slides:
  select_heart:
    widgets:
      - type: text
        text: heartbreaker
        font_size: 36
        color: pink
    transition:
      type: move_in
      direction: right
  select_power:
    widgets:
      - type: text
        text: power
        font_size: 36
        color: purple
    transition:
      type: move_in
      direction: right
  select_multiply:
    widgets:
      - type: text
        text: multiple
        font_size: 36
        color: green
    transition:
      type: move_in
      direction: right 
  
scoring:
  spinner_type_heart_highlighted:
    gametype:
      string: 30flips
      action: set
  spinner_type_power_highlighted:
    gametype:
      string: standard
      action: set
  spinner_type_multiply_highlighted:
    gametype:
      string: access
      action: set